### ISSUE TITLE
Enhancement: Add support for Nordic UI

### ISSUE THREAD

**Issue by Nexusbla18** [WaterFace/CompassNavigationOverhaul#1]
I really love the mod and it's a shame that it has not been updated in a while.
Its great to see that you took the opportunity to make an update.
Obviously, your update does not work for Nordic UI. Could you please make a Nordic UI version, too?

**Comment by WaterFace** [comment]
In my testing it does work with Nordic UI. Get the Nordic UI patch from [the main CNO page](https://www.nexusmods.com/skyrimspecialedition/mods/74484) (it's the optional file) and make sure you have Nordic UI and SkyHUD installed.

Let me know if that works for you.

**Comment by Nexusbla18** [comment]
Yeah, seems like the issue is/was Infinity UI.

Edit: Just discovered that you made an update which only needs the "old" Infinity UI. You are awesome!
